jwt:
  header: Authorization
  secret: ${JWT_SECRET}
  token-validity-in-seconds: 8640000
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
