jwt:
  header: Authorization
  secret: ${JWT_SECRET}
  token-validity-in-seconds: 8640000
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: created
        default_batch_fetch_size: 1000
